(in-package #:parsonic)

(defmethod expand-expr :around ((op symbol) &rest args)
  (destructuring-case (cons op args)
    ((satisfies predicate)
     (if (and (consp predicate) (equal predicate `(curry #'eql ,(caddr predicate))))
         (call-next-method)
         (call-next-method
          op (with-gensyms (result)
               `(lambda (,result)
                  (unless (eq ,result +input-eof+)
                    (funcall ,predicate ,result)))))))
    ((rep parser &optional (from 0) (to most-positive-fixnum))
     (call-next-method op parser from to))
    ((t &rest args) (declare (ignore args)) (call-next-method))))
